nroonga/nroonga

src/nroonga.cc
src/nroonga.h

It is because it was not used in `nan` usage examples.
https://github.com/nodejs/node-addon-examples/tree/6a51626da3438a59d31d43229cee3e6fd09ec8a5/6_object_wrap/nan

Remove namespace v8

---

npm-shrinkwrap.json
package.json

TODO:
```
../src/nroonga.cc: In static member function ‘static void nroonga::Database::CommandAfter(uv_work_t*)’:
../src/nroonga.cc:172:31: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
argc, argv);
^
In file included from ../src/nroonga.h:3:0,
from ../src/nroonga.cc:1:
../node_modules/nan/nan.h:929:46: note: declared here
NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
```

Upgrade packages

---

src/nroonga.cc
src/nroonga.h

> Deprecated wrappers around the legacy node::MakeCallback() APIs. Node.js 10+ has deprecated these legacy APIs as they do not provide a mechanism to preserve async context.
https://github.com/nodejs/nan/blob/master/doc/node_misc.md#nanmakecallback

 Change `Nan::MakeCallback` to `AsyncResource::runInAsyncScope`

---

src/nroonga.cc

The following warning.
```
../src/nroonga.cc:215:61: warning:
‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated:
Use Isolate version [-Wdeprecated-declarations]
v8::String::Utf8Value command(optionsToCommandString(info));
```

Replace `v8::String::Utf8Value` with `Nan::Utf8String`

---

.travis.yml
package.json

Node.js 4.0 is now EOL.
https://github.com/nodejs/Release#end-of-life-releases

Stop supporting Node.js4

---

npm-shrinkwrap.json
package.json
src/nroonga.cc

- Upgrade nan
- Fix deprecated warnings
```
% node -v
v11.6.0
```
Example of warning.
```
../src/nroonga.cc:14:30: warning: ‘v8::Local<v8::String> v8::Value::ToString() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
return info[0]->ToString();
```

Fix deprecated warnings

---

src/nroonga.cc
src/nroonga.h

The following warning.
```
../src/nroonga.cc: In static member function ‘static v8::Local<v8::String> nroonga::Database::Concat(v8::Local<v8::String>, v8::Local<v8::String>)’:
../src/nroonga.cc:9:40: warning: ‘static v8::Local<v8::String> v8::String::Concat(v8::Local<v8::String>, v8::Local<v8::String>)’ is deprecated: Use Isolate* version [-Wdeprecated-declarations]
return v8::String::Concat(left, right);
```

 Fix deprecation of 'v8::String::Concat()'

---

.travis.yml

https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration

Remove 'sudo' settings from .travis.yml

---

.travis.yml
appveyor.yml
test/plugin.test.js

When Groonga plugin module is located under build/Release/*,
it fails to load plugin because of libgroonga.dll can't handle
extended path prefix \\?\ correctly which GetModuleFileNameW returns
it.
If libgroonga.dll has loaded from GROONGA_PATH, it doesn't occur,
so added test case 1. with GROONGA_PATH and 2. without GROONGA_PATH.
Related issue: https://github.com/groonga/groonga/issues/958

appveyor: test extended path prefix \\?\ test case

---

appveyor.yml

11 -> 12
AppVeyor can use Node.js12.

Modify version of AppVeyor's Node.js

---

.travis.yml
package-lock.json
package.json

現在、`npm install nroonga`した時に、必要のないパッケージもインストールしてしまう状態なので、`package-lock.json`に切り替えませんか。
使用パッケージのアップデートは、`package.json`を更新して、`npm install`で`package-lock.json`も更新していく流れになると思うので、`chai`等のバージョン指定を書き加えました。
定期的に`npm-check-updates`で更新していく感じになると思います。
node の version 6 だけnpmが古いようなので、`.travis.yml`にnpmの更新を追加しました。

Use package-lock.json instead of npm-shrinkwrap.json

---

.travis.yml
appveyor.yml
package-lock.json
package.json

* Node.js 6 is EOL
* https://github.com/nodejs/Release#end-of-life-releases
* Also upgrade packages that require Node.js 8 or greater

Drop support Node.js 6

---

examples/test.ts
types/nroonga.d.ts

I got an error.
```
% tsc types/nroonga.d.ts
types/nroonga.d.ts:3:31 - error TS1005: ':' expected.
3     (error: Error, data: any) => void
~~
Found 1 error.
```
Also add a simple TypeScript example.

Fix definition error of `nroonga.d.ts`

---

.github/workflows/workflow.yml
package-lock.json
package.json

The following warning in Node.js14.
```
../node_modules/nan/nan_typedarray_contents.h:34:43: warning: 'GetContents' is deprecated: Use GetBackingStore. See
http://crbug.com/v8/9908. [-Wdeprecated-declarations]
data   = static_cast<char*>(buffer->GetContents().Data()) + byte_offset;
```
I upgraded the other packages with `npm update`.
Node.js13 is not an LTS, so change it to Node.js14 in the LTS.

Support Node.js 14

---

.github/workflows/workflow.yml
package.json

* Node.js 8 is EOL.
* https://github.com/nodejs/Release#end-of-life-releases
* The latest version of npm does not support Node.js8.
* `npm WARN npm npm does not support Node.js v8.17.0`

Drop Node.js 8.x support

---

.github/workflows/workflow.yml

Node.js16 has been released.
https://nodejs.org/

ci: add 16.x to node-version

---

.github/workflows/workflow.yml

'windows-latest' is the transition period from '2019' to '2022'.
So we do not know which one it will be.
https://github.blog/changelog/2021-11-16-github-actions-windows-server-2022-with-visual-studio-2022-is-now-generally-available-on-github-hosted-runners/

ci: use windows-2022 explicitly

---

.github/workflows/workflow.yml

Node.js 10 is EOL.
https://github.com/nodejs/Release#end-of-life-releases

ci: drop 10.x from node-version

---

.github/workflows/workflow.yml

* ci: drop 12.x from node-version
* 12 is EOL.
* ci: change windows image to 'windows-latest'
* The windows-latest label currently uses the Windows Server 2022 runner image.
* ci: delete unnecessary configuration commands
* The following error occurred. ```npm ERR! `msvs_version` is not a valid npm option```
* It continues to fail only on Windows 14.x, but I believe this will be fixed when the image is updated in the future.

Update CI settings

---

test/plugin.test.js

When installing Groonga on Mac with Homebrew, Ruby plugin is no longer included. 
https://github.com/Homebrew/homebrew-core/pull/126947

Skip Ruby plugin test on Mac

---

.github/workflows/workflow.yml

https://github.com/nodejs/Release
* Drop 14.x
* EOL on 2023-04-30
* Add 20.x
* Released on 2023-04-18

ci: update `node-version`

---

.github/workflows/workflow.yml

The latest npm may not support the version of Node.js used in CI.
https://github.com/nroonga/nroonga/actions/runs/6218329794/job/16874657692?pr=103

ci: use npm already installed on windows

---

.github/workflows/workflow.yml
binding.gyp

* 16.x is EOL, so it is dropped
* Add `"defines": ["NOMINMAX"]`
* We got this error in Windows: 
```
C:\Users\runneradmin\AppData\Local\node-gyp\Cache\22.1.0\include\node\v8-function-callback.h(408,62): warning C4003: not enough arguments for function-like macro invocation 'min' [D:\a\nroonga\nroonga\build\nroonga_bindings.vcxproj]
(compiling source file '../src/nroonga.cc')
C:\Users\runneradmin\AppData\Local\node-gyp\Cache\22.1.0\include\node\v8-function-callback.h(409,62): warning C4003: not enough arguments for function-like macro invocation 'max' [D:\a\nroonga\nroonga\build\nroonga_bindings.vcxproj]
(compiling source file '../src/nroonga.cc')
C:\Users\runneradmin\AppData\Local\node-gyp\Cache\22.1.0\include\node\v8-function-callback.h(408,62): error C2589: '(': illegal token on right …
```

ci: add 22.x to node-version

---

.github/workflows/workflow.yml

Update to the currently supported version.
https://github.com/nodejs/Release
Add 24.x
Drop 18.x

ci: Update node-version
